version: '3.9'
services:
  ubuntu-gnome:
    hostname: uDesk.local.skoona.net
    image: net-skoona-development-webtop-ubuntu-image:vl-1.2
    container_name: WebTop-Gnome-uDesktop
    privileged: true
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=America/Indiana/Indianapolis
      - SUBFOLDER=/ 
      - TITLE=Skoona uDesktop
    networks:
      vlan20:
        ipv4_address: 10.100.20.11
    volumes:
    - type: volume
      source: cDevelopment
      target: /Projects
    - type: volume
      source: webtop-homes
      target: /home
    - type: volume
      source: webtop-home-ubuntu
      target: /config
    restart: unless-stopped
    
volumes:
  cDevelopment:
    external: true
  webtop-homes:
    external: true
  webtop-home-ubuntu:
    external: true

networks:
  vlan20:
    name: iot-dev-network
    driver: macvlan
    driver_opts:
      parent: ens18.20
    ipam:
      config:
        - subnet: "10.100.20.0/24"
          gateway: "10.100.20.1"
