#!/usr/bin/env bash
#
# file: dBuild <index> <tag>
# - Build One Development image
# - <index>: 0 to 5, based on IMAGES
# - <tag>: docker-image:<tag>
#

INDEX=${1:-0}
TAG=${2:-3.1.0}

IMAGES=( net-skoona-development-gtk-image:$TAG \
    net-skoona-development-cpp-image:$TAG \
    net-skoona-development-golang-image:$TAG \
    net-skoona-development-espressif-image:$TAG \
    net-skoona-development-ruby-image:$TAG \
    net-skoona-development-arduino-image:$TAG )

WORKDIRS=( docker-elementary-gtk \
    docker-elementary-cpp \
    docker-elementary-golang \
    docker-elementary-espressif \
    docker-elementary-ruby \
    docker-elementary-arduino )

# set mkpasswd 
 [[ -s ./.export-user-secrets ]] && {
     source ./.export-user-secrets
 } || { 
    source ./.user-secrets
 } 

pushd "./${WORKDIRS[$INDEX]}"
   [[ -d .ssh ]] || {
      cp -a ../.ssh . 
      cp ../.bashrc .
   }
  docker build --build-arg SC_JSCOTT --build-arg SC_SKOONA --build-arg SC_DEVELOPER -t ${IMAGES[$INDEX]} .
popd

echo "Done..."
