#!/usr/bin/env bash
#
# file: dMake <version>
#
# Build Development Stack
#
#

TAG="${1:-3.1.0}"

IMAGES=( net-skoona-development-gtk-image:$TAG \
    net-skoona-development-cpp-image:$TAG \
    net-skoona-development-golang-image:$TAG \
    net-skoona-development-espressif-image:$TAG \
    net-skoona-development-ruby-image:$TAG \
    net-skoona-development-arduino-image:$TAG )


WORKDIRS=( docker-elementary-gtk \
    docker-elementary-cpp \
    docker-elementary-golang \
    docker-elementary-espressif \
    docker-elementary-ruby \
    docker-elementary-arduino )

export SC_TAG=$TAG

# set mkpasswd 
 [[ -s ./.export-user-secrets ]] && {
     source ./.export-user-secrets
 } || { 
    source ./.user-secrets
 } 

for i in {0..5} ; do
    pushd "./${WORKDIRS[$i]}"
    [[ -d .ssh ]] || {
        cp -a ../.ssh . 
        cp ../.bashrc .
    }

    docker build -q --build-arg SC_JSCOTT --build-arg SC_SKOONA --build-arg SC_DEVELOPER --build-arg SC_TAG -t ${IMAGES[$i]} .
    
    popd
done

[[ -s docker-compose-devcons.yml ]] && { 
    rm -f docker-compose-devcons.yml 
}
sed "s/LATEST/$TAG/g" stack-docker-compose.yml > docker-compose-devcons.yml

echo "Done..."
