version: '3.9'
services:
  elementary-gnome:
    container_name: Elementary-Gnome-Desktop
    image: net-skoona-development-elementary-image:LATEST
    networks:
      vlan20:
        ipv4_address: 10.100.20.12
    restart: always
    tty: true
    volumes:
      - type: volume
        source: cDevelopment
        target: /Projects

  ubuntu-gnome:
    container_name: Ubuntu-Gnome-Desktop
    image: net-skoona-development-ubuntu-image:LATEST
    networks:
      vlan20:
        ipv4_address: 10.100.20.11
    restart: always
    tty: true
    volumes:
      - type: volume
        source: cDevelopment
        target: /Projects

volumes:
  cDevelopment:
    external: true

networks:
  vlan20:
    name: iot-dev-network
    driver: macvlan
    driver_opts:
      parent: ens18.20
    ipam:
      config:
        - subnet: "10.100.20.0/24"
          gateway: "10.100.20.1"
