---
version: '3.9'
services:
  cppdev:
    container_name: CPP-Development
    environment:
      - DISPLAY=10.100.1.5:0.1
    image: net-skoona-development-cpp-image:LATEST
    ports:
      - target: 22
        published: 410
        protocol: tcp
        mode: bridge
      - target: 80
        published: 8010
        protocol: tcp
        mode: bridge
      - target: 3389
        published: 4310
        protocol: tcp
        mode: bridge
      - target: 5900
        published: 5910
        protocol: tcp
        mode: bridge
    restart: always
    tty: true
    volumes:
      - type: volume
        source: cDevelopment
        target: /Projects

  gtk4dev:
    container_name: Gtk4-Development
    environment:
      - DISPLAY=10.100.1.5:0.1
    image: net-skoona-development-gtk-image:LATEST
    ports:
      - target: 22
        published: 420
        protocol: tcp
        mode: bridge
      - target: 80
        published: 8020
        protocol: tcp
        mode: bridge
      - target: 3389
        published: 4320
        protocol: tcp
        mode: bridge
      - target: 5900
        published: 5920
        protocol: tcp
        mode: bridge
    restart: always
    tty: true
    volumes:
      - type: volume
        source: cDevelopment
        target: /Projects

  godev:
    container_name: Golang-Development
    environment:
      - DISPLAY=10.100.1.5:0.1
    image: net-skoona-development-golang-image:LATEST
    ports:
      - target: 22
        published: 430
        protocol: tcp
        mode: bridge
      - target: 80
        published: 8030
        protocol: tcp
        mode: bridge
      - target: 3389
        published: 4330
        protocol: tcp
        mode: bridge
      - target: 5900
        published: 5930
        protocol: tcp
        mode: bridge
    restart: always
    tty: true
    volumes:
      - type: volume
        source: cDevelopment
        target: /Projects

  rubydev:
    container_name: Ruby-Development
    environment:
      - RACK_ENV=development
      - DISPLAY=10.100.1.5:0.1
    image: net-skoona-development-ruby-image:LATEST
    ports:
      - target: 22
        published: 440
        protocol: tcp
        mode: bridge
      - target: 80
        published: 8040
        protocol: tcp
        mode: bridge
      - target: 3000
        published: 3040
        protocol: tcp
        mode: bridge
      - target: 3389
        published: 4340
        protocol: tcp
        mode: bridge
      - target: 5900
        published: 5940
        protocol: tcp
        mode: bridge
    restart: always
    tty: true
    volumes:
      - type: volume
        source: cDevelopment
        target: /Projects
 
  espdev:
    container_name: ESP-Development
    environment:
      - DISPLAY=10.100.1.5:0.1
    image: net-skoona-development-espressif-image:LATEST
    ports:
      - target: 22
        published: 450
        protocol: tcp
        mode: bridge
      - target: 80
        published: 8050
        protocol: tcp
        mode: bridge
      - target: 3389
        published: 4350
        protocol: tcp
        mode: bridge
      - target: 5900
        published: 5950
        protocol: tcp
        mode: bridge
    restart: always
    tty: true
    volumes:
      - type: volume
        source: cDevelopment
        target: /Projects

  arduino:
    container_name: Arduino-Development
    environment:
      - DISPLAY=10.100.1.5:0.1
    image: net-skoona-development-arduino-image:LATEST
    ports:
      - target: 22
        published: 460
        protocol: tcp
        mode: bridge
      - target: 80
        published: 8060
        protocol: tcp
        mode: bridge
      - target: 3389
        published: 4360
        protocol: tcp
        mode: bridge
      - target: 5900
        published: 5960
        protocol: tcp
        mode: bridge
    restart: always
    tty: true
    volumes:
      - type: volume
        source: cDevelopment
        target: /Projects

volumes:
  cDevelopment:
    external: true
    