version: '3.9'
services:
  elementary-gnome:
    container_name: Elementary-Gnome-Desktop
    environment:
      - DISPLAY=10.100.1.5:0.1
    image: net-skoona-development-elementary-image:LATEST
    ports:
      - target: 22
        published: 470
        protocol: tcp
        mode: bridge
      - target: 80
        published: 8070
        protocol: tcp
        mode: bridge
      - target: 3389
        published: 4370
        protocol: tcp
        mode: bridge
      - target: 5900
        published: 5970
        protocol: tcp
        mode: bridge
    restart: always
    tty: true
    volumes:
      - type: volume
        source: cDevelopment
        target: /Projects

  ubuntu-gnome:
    container_name: Ubuntu-Gnome-Desktop
    environment:
      - DISPLAY=10.100.1.5:0.1
    image: net-skoona-development-ubuntu-image:LATEST
    ports:
      - target: 22
        published: 480
        protocol: tcp
        mode: bridge
      - target: 80
        published: 8080
        protocol: tcp
        mode: bridge
      - target: 3389
        published: 4380
        protocol: tcp
        mode: bridge
      - target: 5900
        published: 5980
        protocol: tcp
        mode: bridge
    restart: always
    tty: true
    volumes:
      - type: volume
        source: cDevelopment
        target: /Projects

volumes:
  cDevelopment:
    external: true
