version: '3.9'
services:
  rubydev:
    container_name: Ruby-Development
    environment:
      - RACK_ENV=development
      - DISPLAY=10.100.1.5:0.1
    image: net-skoona-rubydev-image:1.0.0
    ports:
      - target: 22
        published: 465
        protocol: tcp
        mode: bridge
      - target: 5900
        published: 10000
        protocol: tcp
        mode: bridge
      - target: 80
        published: 8086
        protocol: tcp
        mode: bridge
      - target: 3000
        published: 3004
        protocol: tcp
        mode: bridge
    restart: always
    tty: true
    volumes:
      - type: volume
        source: cDevelopment
        target: /Projects

volumes:
  cDevelopment:
    external: true
    
