version: '3.9'
services:
  godev:
    container_name: Golang-Development
    environment:
      - DISPLAY=10.100.1.5:0.1
    image: net-skoona-development-godev-image:1.0.0
    networks:
      vlan20:
        ipv4_address: 10.100.20.5
    restart: always
    tty: true
    volumes:
      - type: volume
        source: cDevelopment
        target: /Projects

volumes:
  cDevelopment:
    external: true
   
networks:
  vlan20:
    name: iot-dev-network
    driver: macvlan
    driver_opts:
      parent: ens18.20
    ipam:
      config:
        - subnet: "10.100.20.0/24"
          gateway: "10.100.20.1"
